version: "3"
services:
  frontend:
    build:
      context: ./my-app/
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - ${FRONTEND_PORT}:1234
    volumes:
      - /usr/src/app/node_modules
      - ./my-app:/usr/src/app/
